### ISSUE TITLE
[Bug] Buttons overlap with Physics Mod (Pro)

### ISSUE THREAD

**Issue by nco2k** [Estecka/mc-PackRule-Menus#9]
![bug](https://github.com/Estecka/mc-PackRule-Menus/assets/26080123/cdf0347b-ee85-4202-a808-f7ad99806265)

**Comment by Estecka** [comment]
This issue comes from PhysicsMod.
Unfortunately, their mod is closed-source, so no-one but them have the ability fix this. I was able to peek at their code by decompiling the mod's jar, but I wouldn't be able to easily make change to it nor submit a PR for this.
This should be reported to them.

In PackruleMenu, I place the buttons by using Mojang's `Gridwidget.adder` (Yarn mappings), which is used to place all vanilla buttons. This method automatically adapts the menu's layout to its content, so this kind of issue would never happen amongst buttons registered in this way.

The issue is that physics Mod **does not** use the `Gridwidget.adder`, and instead places its button at fixed coordinates, assuming this position would always be empty.
